_core:
  default_config_hash: c8aZhkIY8zHUo0_UOll4vVs_l48dHL_gBqbvfuAM0Rs
favicon:
  path: profiles/farm/modules/core/ui/theme/favicon.ico
  use_default: false
logo:
  path: profiles/farm/modules/core/ui/theme/logo.png
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: green
preset_focus_color: orange
enable_darkmode: '0'
classic_toolbar: vertical
secondary_toolbar_frontend: true
high_contrast_mode: false
layout_density: default
show_description_toggle: false
show_user_theme_settings: true
sticky_action_buttons: false
